# Sample .travis.yml for R projects

language: r
#warnings_are_errors: true
sudo: required
#bioc_required: false

before_script:
  - sudo apt-get install -y jags

# before_install:
#  - sudo apt-get install r-cran-rjags -y

# r_packages:
#  - coda
#  - dplyr
#  - epitools
#  - ggplot2
#  - gridExtra
#  - reshape2
#  - stringr
#  - knitr
#  - rmarkdown
#  - testthat
